# INC, TARGET is need define by user before inclue this file
# The define is such as:
# INC := -I ../src
# TARGET := libother.a

CC := gcc
CFLAG += -g -Wall -O

SRC := ${wildcard *.c}
DEP := $(SRC:.c=.d)
OBJ := $(SRCS:.c=.o)

all: $(OBJ)
	ar -r $(TARGET) $(OBJ)

$(OBJ): %.o: %.c
	$(CC) -c $< -o $@ $(INC) $(CFLAG)

$(DEP):%.d:%.c
	rm -f $@;
	$(CC) -MM $< $(INC) > $@

-include $(DEP)

clean:
	-rm -f $(TARGET) *.o *.d
